language: c

sudo: false

addons:
  apt:
    packages:
    - wget
    - libgmp-dev
    - libffi6
    - libc6:i386

before_install:
 # install Futhark
 - wget http://futhark-lang.org/releases/futhark-nightly-linux-x86_64.tar.xz
 - tar xf futhark-nightly-linux-x86_64.tar.xz
 - (cd futhark-nightly-linux-x86_64/ && PREFIX=$HOME/.local make install)

script:
  - futhark test --notty --pass-compiler-option=--Werror -C .
