name: CI

on:
  pull_request:
    branches: [ master ]

  push:
    branches: [ master ]

  # Run weekly to detect compiler or dependency regressions.
  schedule:
    - cron: "0 0 * * 0"

jobs:
  test-on-nightly:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Futhark
      uses: diku-dk/install-futhark@v1.1.0
      with:
        version: 'nightly'

    - run: futhark test -C --pass-compiler-option=--Werror *
